_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_episode_storage:
    value: None
_last_episode_starts:
    value: '[ True]'
_last_obs:
    value: |-
        [[-1.0200582e-03  1.0184127e-04  7.0931548e-03  2.0826400e-04
          -2.0826400e-04  0.0000000e+00  0.0000000e+00  6.3863159e-03
           9.9493866e-04  9.9493866e-04  6.4090132e-03  1.0200582e-03
          -1.0184127e-04 -1.7367932e-03  1.9850049e-03  8.9445384e-04
          -1.6889822e-03  9.9493866e-04  9.9493866e-04  4.9994374e-05
           7.0707141e-03  0.0000000e+00  0.0000000e+00  0.0000000e+00
           0.0000000e+00]]
_last_original_obs:
    value: |-
        [[-0.10255095  0.01018567  1.0063772   0.020833   -0.020833    0.
           0.          0.83        0.1         0.1         0.835       0.10255095
          -0.01018567 -0.17637722  0.20255095  0.08981433 -0.17137721  0.1
           0.1         0.005       1.          0.          0.          0.
           0.        ]]
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x7f770ae57310>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 100000
_vec_normalize_env:
    value: <stable_baselines3.common.vec_env.vec_normalize.VecNormalize object at 0x7f770beb1050>
_wandb:
    value:
        cli_version: 0.18.7
        code_path: code/reward_machines/reward_machines/run_robosuite.py
        m: []
        python_version: 3.7.12
        t:
            "1":
                - 1
                - 3
                - 55
            "2":
                - 1
                - 3
                - 55
            "3":
                - 1
                - 16
                - 22
                - 23
                - 35
                - 55
            "4": 3.7.12
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
action_noise:
    value: NormalActionNoise(mu=[0. 0. 0. 0. 0. 0. 0.], sigma=[0.2 0.2 0.2 0.2 0.2 0.2 0.2])
action_space:
    value: Box(-1.0, 1.0, (7,), float32)
actor:
    value: |-
        Actor(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (mu): Sequential(
            (0): Linear(in_features=25, out_features=400, bias=True)
            (1): ReLU()
            (2): Linear(in_features=400, out_features=300, bias=True)
            (3): ReLU()
            (4): Linear(in_features=300, out_features=7, bias=True)
            (5): Tanh()
          )
        )
actor_batch_norm_stats:
    value: '[]'
actor_batch_norm_stats_target:
    value: '[]'
actor_target:
    value: |-
        Actor(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (mu): Sequential(
            (0): Linear(in_features=25, out_features=400, bias=True)
            (1): ReLU()
            (2): Linear(in_features=400, out_features=300, bias=True)
            (3): ReLU()
            (4): Linear(in_features=300, out_features=7, bias=True)
            (5): Tanh()
          )
        )
algo:
    value: DDPG
batch_size:
    value: 100
buffer_size:
    value: 1000000
critic:
    value: |-
        ContinuousCritic(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (qf0): Sequential(
            (0): Linear(in_features=32, out_features=400, bias=True)
            (1): ReLU()
            (2): Linear(in_features=400, out_features=300, bias=True)
            (3): ReLU()
            (4): Linear(in_features=300, out_features=1, bias=True)
          )
        )
critic_batch_norm_stats:
    value: '[]'
critic_batch_norm_stats_target:
    value: '[]'
critic_target:
    value: |-
        ContinuousCritic(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (qf0): Sequential(
            (0): Linear(in_features=32, out_features=400, bias=True)
            (1): ReLU()
            (2): Linear(in_features=400, out_features=300, bias=True)
            (3): ReLU()
            (4): Linear(in_features=300, out_features=1, bias=True)
          )
        )
device:
    value: cuda
env:
    value: <stable_baselines3.common.vec_env.vec_normalize.VecNormalize object at 0x7f770beb1050>
env_name:
    value: robosuite
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
gamma:
    value: 0.9
gradient_steps:
    value: -1
learning_rate:
    value: 0.0001
learning_starts:
    value: 100
lr_schedule:
    value: <function constant_fn.<locals>.func at 0x7f770bebd8c0>
n_envs:
    value: 1
num_timesteps:
    value: 0
observation_space:
    value: Box(-inf, inf, (25,), float32)
optimize_memory_usage:
    value: "False"
policy:
    value: |-
        TD3Policy(
          (actor): Actor(
            (features_extractor): FlattenExtractor(
              (flatten): Flatten(start_dim=1, end_dim=-1)
            )
            (mu): Sequential(
              (0): Linear(in_features=25, out_features=400, bias=True)
              (1): ReLU()
              (2): Linear(in_features=400, out_features=300, bias=True)
              (3): ReLU()
              (4): Linear(in_features=300, out_features=7, bias=True)
              (5): Tanh()
            )
          )
          (actor_target): Actor(
            (features_extractor): FlattenExtractor(
              (flatten): Flatten(start_dim=1, end_dim=-1)
            )
            (mu): Sequential(
              (0): Linear(in_features=25, out_features=400, bias=True)
              (1): ReLU()
              (2): Linear(in_features=400, out_features=300, bias=True)
              (3): ReLU()
              (4): Linear(in_features=300, out_features=7, bias=True)
              (5): Tanh()
            )
          )
          (critic): ContinuousCritic(
            (features_extractor): FlattenExtractor(
              (flatten): Flatten(start_dim=1, end_dim=-1)
            )
            (qf0): Sequential(
              (0): Linear(in_features=32, out_features=400, bias=True)
              (1): ReLU()
              (2): Linear(in_features=400, out_features=300, bias=True)
              (3): ReLU()
              (4): Linear(in_features=300, out_features=1, bias=True)
            )
          )
          (critic_target): ContinuousCritic(
            (features_extractor): FlattenExtractor(
              (flatten): Flatten(start_dim=1, end_dim=-1)
            )
            (qf0): Sequential(
              (0): Linear(in_features=32, out_features=400, bias=True)
              (1): ReLU()
              (2): Linear(in_features=400, out_features=300, bias=True)
              (3): ReLU()
              (4): Linear(in_features=300, out_features=1, bias=True)
            )
          )
        )
policy_class:
    value: <class 'stable_baselines3.td3.policies.TD3Policy'>
policy_delay:
    value: 1
policy_kwargs:
    value: '{''n_critics'': 1}'
policy_type:
    value: MlpPolicy
replay_buffer:
    value: <stable_baselines3.common.buffers.ReplayBuffer object at 0x7f770ae58f90>
replay_buffer_class:
    value: <class 'stable_baselines3.common.buffers.ReplayBuffer'>
replay_buffer_kwargs:
    value: '{}'
reward_scale:
    value: 1
sde_sample_freq:
    value: -1
seed:
    value: None
start_time:
    value: 1732119574924408761
target_noise_clip:
    value: 0
target_policy_noise:
    value: 0.1
tau:
    value: 0.01
tensorboard_log:
    value: runs/d9vdeal0
total_timesteps:
    value: 100000
train_freq:
    value: 'TrainFreq(frequency=1, unit=<TrainFrequencyUnit.EPISODE: ''episode''>)'
use_sde:
    value: "False"
use_sde_at_warmup:
    value: "False"
verbose:
    value: 1
